--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12 (Homebrew)
-- Dumped by pg_dump version 14.12 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: ko; Type: SCHEMA; Schema: -; Owner: andreasehrencrona
--

CREATE SCHEMA ko;


ALTER SCHEMA ko OWNER TO andreasehrencrona;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.activity (
    user_id integer NOT NULL,
    date date DEFAULT now() NOT NULL,
    words_known integer NOT NULL,
    minutes_spent integer DEFAULT 0,
    sentences_done integer DEFAULT 0 NOT NULL,
    words_known_write integer NOT NULL
);


ALTER TABLE ko.activity OWNER TO andreasehrencrona;

--
-- Name: aggregate_knowledge; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.aggregate_knowledge (
    user_id integer NOT NULL,
    word_id integer NOT NULL,
    "time" timestamp with time zone NOT NULL,
    alpha real NOT NULL,
    beta real
);


ALTER TABLE ko.aggregate_knowledge OWNER TO andreasehrencrona;

--
-- Name: knowledge; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.knowledge (
    user_id integer NOT NULL,
    word_id integer NOT NULL,
    sentence_id integer,
    knew boolean NOT NULL,
    "time" timestamp with time zone DEFAULT now() NOT NULL,
    studied_word_id integer,
    type integer NOT NULL
);


ALTER TABLE ko.knowledge OWNER TO andreasehrencrona;

--
-- Name: mnemonics; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.mnemonics (
    word_id integer NOT NULL,
    user_id integer NOT NULL,
    mnemonic character varying NOT NULL
);


ALTER TABLE ko.mnemonics OWNER TO andreasehrencrona;

--
-- Name: sentences; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.sentences (
    id integer NOT NULL,
    sentence character varying NOT NULL,
    english character varying,
    user_id integer,
    level integer DEFAULT 100 NOT NULL
);


ALTER TABLE ko.sentences OWNER TO andreasehrencrona;

--
-- Name: sentences_id_seq; Type: SEQUENCE; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ko.sentences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ko.sentences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sentences_seen; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.sentences_seen (
    user_id integer NOT NULL,
    sentence_id integer NOT NULL,
    "time" timestamp with time zone DEFAULT now() NOT NULL,
    times integer DEFAULT 1 NOT NULL
);


ALTER TABLE ko.sentences_seen OWNER TO andreasehrencrona;

--
-- Name: user_exercises; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.user_exercises (
    sentence_id integer NOT NULL,
    word_id integer,
    user_id integer NOT NULL,
    exercise_type integer NOT NULL,
    alpha real NOT NULL,
    beta real,
    last_time timestamp with time zone DEFAULT now() NOT NULL,
    level integer NOT NULL
);


ALTER TABLE ko.user_exercises OWNER TO andreasehrencrona;

--
-- Name: word_lemma; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.word_lemma (
    word character varying NOT NULL,
    lemma_id integer NOT NULL
);


ALTER TABLE ko.word_lemma OWNER TO andreasehrencrona;

--
-- Name: word_sentences; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.word_sentences (
    word_id integer NOT NULL,
    sentence_id integer NOT NULL,
    word_index smallint NOT NULL
);


ALTER TABLE ko.word_sentences OWNER TO andreasehrencrona;

--
-- Name: word_translations; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.word_translations (
    word_id integer NOT NULL,
    sentence_id integer,
    english character varying NOT NULL,
    form character varying
);


ALTER TABLE ko.word_translations OWNER TO andreasehrencrona;

--
-- Name: words; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.words (
    id integer NOT NULL,
    word character varying(255) NOT NULL,
    json json,
    level integer DEFAULT 100 NOT NULL,
    cognate boolean
);


ALTER TABLE ko.words OWNER TO andreasehrencrona;

--
-- Name: words_id_seq; Type: SEQUENCE; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ko.words ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ko.words_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: written_sentences; Type: TABLE; Schema: ko; Owner: andreasehrencrona
--

CREATE TABLE ko.written_sentences (
    id integer NOT NULL,
    sentence character varying NOT NULL,
    user_id integer NOT NULL,
    word_id integer,
    "time" timestamp with time zone DEFAULT now() NOT NULL,
    entered character varying
);


ALTER TABLE ko.written_sentences OWNER TO andreasehrencrona;

--
-- Name: written_sentences_id_seq; Type: SEQUENCE; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ko.written_sentences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME ko.written_sentences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: aggregate_knowledge aggregate_knowledge_user_id_word_id_key; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.aggregate_knowledge
    ADD CONSTRAINT aggregate_knowledge_user_id_word_id_key UNIQUE (user_id, word_id);


--
-- Name: mnemonics mnemonics_pkey; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.mnemonics
    ADD CONSTRAINT mnemonics_pkey PRIMARY KEY (word_id, user_id);


--
-- Name: sentences sentences_pkey; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.sentences
    ADD CONSTRAINT sentences_pkey PRIMARY KEY (id);


--
-- Name: sentences_seen sentences_seen_pkey; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.sentences_seen
    ADD CONSTRAINT sentences_seen_pkey PRIMARY KEY (sentence_id, user_id);


--
-- Name: sentences sentences_sentence_key; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.sentences
    ADD CONSTRAINT sentences_sentence_key UNIQUE (sentence);


--
-- Name: user_exercises user_exercises_user_id_sentence_id_word_id_key; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.user_exercises
    ADD CONSTRAINT user_exercises_user_id_sentence_id_word_id_key UNIQUE (sentence_id, user_id, word_id);


--
-- Name: activity vocab_size_pkey; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.activity
    ADD CONSTRAINT vocab_size_pkey PRIMARY KEY (user_id, date);


--
-- Name: word_lemma word_lemma_word_lemma_id_key; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_lemma
    ADD CONSTRAINT word_lemma_word_lemma_id_key UNIQUE (word, lemma_id);


--
-- Name: word_sentences word_sentences_pkey; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_sentences
    ADD CONSTRAINT word_sentences_pkey PRIMARY KEY (word_id, sentence_id, word_index);


--
-- Name: word_translations word_translations_word_id_sentence_id_key; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_translations
    ADD CONSTRAINT word_translations_word_id_sentence_id_key UNIQUE (word_id, sentence_id);


--
-- Name: words words_pkey; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.words
    ADD CONSTRAINT words_pkey PRIMARY KEY (id);


--
-- Name: words words_word_key; Type: CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.words
    ADD CONSTRAINT words_word_key UNIQUE (word);


--
-- Name: idx_pl_user_exercises_user_id; Type: INDEX; Schema: ko; Owner: andreasehrencrona
--

CREATE INDEX idx_pl_user_exercises_user_id ON ko.user_exercises USING btree (user_id);


--
-- Name: idx_sentences_level; Type: INDEX; Schema: ko; Owner: andreasehrencrona
--

CREATE INDEX idx_sentences_level ON ko.sentences USING btree (level);


--
-- Name: idx_word_sentences_word_id; Type: INDEX; Schema: ko; Owner: andreasehrencrona
--

CREATE INDEX idx_word_sentences_word_id ON ko.word_sentences USING btree (word_id);


--
-- Name: sentence; Type: INDEX; Schema: ko; Owner: andreasehrencrona
--

CREATE INDEX sentence ON ko.knowledge USING btree (sentence_id);


--
-- Name: unique_user_sentence_null_word_pl; Type: INDEX; Schema: ko; Owner: andreasehrencrona
--

CREATE UNIQUE INDEX unique_user_sentence_null_word_pl ON ko.user_exercises USING btree (user_id, sentence_id) WHERE (word_id IS NULL);


--
-- Name: word_lemma_word_idx; Type: INDEX; Schema: ko; Owner: andreasehrencrona
--

CREATE INDEX word_lemma_word_idx ON ko.word_lemma USING btree (word) WITH (deduplicate_items='true');


--
-- Name: words_level_idx; Type: INDEX; Schema: ko; Owner: andreasehrencrona
--

CREATE INDEX words_level_idx ON ko.words USING btree (level) WITH (deduplicate_items='true');


--
-- Name: activity activity_user_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.activity
    ADD CONSTRAINT activity_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(num) ON DELETE CASCADE;


--
-- Name: aggregate_knowledge aggregate_knowledge_user_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.aggregate_knowledge
    ADD CONSTRAINT aggregate_knowledge_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(num) ON DELETE CASCADE;


--
-- Name: aggregate_knowledge aggregate_knowledge_word_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.aggregate_knowledge
    ADD CONSTRAINT aggregate_knowledge_word_id_fkey FOREIGN KEY (word_id) REFERENCES ko.words(id) ON DELETE CASCADE NOT VALID;


--
-- Name: sentences fk_pl_sentences_user_id; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.sentences
    ADD CONSTRAINT fk_pl_sentences_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(num);


--
-- Name: knowledge knowledge_sentence_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.knowledge
    ADD CONSTRAINT knowledge_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES ko.sentences(id) ON DELETE CASCADE NOT VALID;


--
-- Name: knowledge knowledge_user_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.knowledge
    ADD CONSTRAINT knowledge_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(num) ON DELETE CASCADE;


--
-- Name: knowledge knowledge_word_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.knowledge
    ADD CONSTRAINT knowledge_word_id_fkey FOREIGN KEY (word_id) REFERENCES ko.words(id) ON DELETE CASCADE NOT VALID;


--
-- Name: mnemonics mnemonics_user_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.mnemonics
    ADD CONSTRAINT mnemonics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(num) ON DELETE CASCADE;


--
-- Name: mnemonics mnemonics_word_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.mnemonics
    ADD CONSTRAINT mnemonics_word_id_fkey FOREIGN KEY (word_id) REFERENCES ko.words(id) NOT VALID;


--
-- Name: sentences_seen sentences_seen_user_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.sentences_seen
    ADD CONSTRAINT sentences_seen_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(num) ON DELETE CASCADE;


--
-- Name: user_exercises user_exercises_sentence_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.user_exercises
    ADD CONSTRAINT user_exercises_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES ko.sentences(id);


--
-- Name: user_exercises user_exercises_user_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.user_exercises
    ADD CONSTRAINT user_exercises_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(num);


--
-- Name: user_exercises user_exercises_word_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.user_exercises
    ADD CONSTRAINT user_exercises_word_id_fkey FOREIGN KEY (word_id) REFERENCES ko.words(id);


--
-- Name: word_lemma word_lemma_lemma_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_lemma
    ADD CONSTRAINT word_lemma_lemma_id_fkey FOREIGN KEY (lemma_id) REFERENCES ko.words(id) ON DELETE CASCADE NOT VALID;


--
-- Name: word_sentences word_sentences_sentence_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_sentences
    ADD CONSTRAINT word_sentences_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES ko.sentences(id) ON DELETE CASCADE NOT VALID;


--
-- Name: word_sentences word_sentences_word_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_sentences
    ADD CONSTRAINT word_sentences_word_id_fkey FOREIGN KEY (word_id) REFERENCES ko.words(id) ON DELETE CASCADE NOT VALID;


--
-- Name: word_translations word_translations_sentence_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_translations
    ADD CONSTRAINT word_translations_sentence_id_fkey FOREIGN KEY (sentence_id) REFERENCES ko.sentences(id) ON DELETE CASCADE;


--
-- Name: word_translations word_translations_word_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.word_translations
    ADD CONSTRAINT word_translations_word_id_fkey FOREIGN KEY (word_id) REFERENCES ko.words(id) ON DELETE CASCADE;


--
-- Name: written_sentences written_sentences_user_id_fkey; Type: FK CONSTRAINT; Schema: ko; Owner: andreasehrencrona
--

ALTER TABLE ONLY ko.written_sentences
    ADD CONSTRAINT written_sentences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.auth_user(num) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

